//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularLearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDetail
    {
        public int UsersDetailID { get; set; }
        public bool CurrentCode { get; set; }
        public int UserID { get; set; }
        public string WorkPhone { get; set; }
        public string MobPhone { get; set; }
        public string HomePhone { get; set; }
        public string HomeAddress { get; set; }
        public string HomeSuburb { get; set; }
        public string HomeState { get; set; }
        public string HomePostcode { get; set; }
        public string MailAddress { get; set; }
        public string MailSuburb { get; set; }
        public string MailState { get; set; }
        public string MailPostcode { get; set; }
        public bool MailSameAsHome { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
